#! /usr/bin/make

help:
	@echo ''
	@echo 'Usage: make [command]'
	@echo ''
	@echo 'Commands:'
	@echo ''
	@echo '  test       Run unit tests'
	@echo ''


test:
	@go test -count=1 `go list ./...`
