package migrations

type LogQuery struct {
	Name        string
	Description string
	Severity    string
	Query       string
}

var LogQueries = map[string]LogQuery{
	"9e4fa2ff-ad7a-4ab2-8337-bcd01b8a6b10": {Name: "Uncorrected Bad Block Search", Description: "Uncorrected Bad Block Search", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SEVERITY","values":["2"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_EVENT","values":["LOG_RAID_UNCORRECTED_BAD_BLOCKS"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"86b1c4e8-32b5-48ec-88e2-822916ef6b57": {Name: "Virtual Disks set to Critical State", Description: "LOG_ST_SET_CRITICAL STATE VIRTUAL DISK", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SEVERITY","values":["2"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_EVENT","values":["LOG_ST_SET_CRITICAL"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"0feaf6f0-87d5-4837-8a5a-2768cc3a2d8c": {Name: "Kernel null pointer", Description: "A kernel null pointer has occurred - updated", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["kernel NULL pointer"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"ce627863-2775-49af-8c7e-ba026ad8b29d": {Name: "LustreError", Description: "A Lustre Error has occurred", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["LustreError"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"38fd12f0-5798-4b93-8d48-abc9719c2d21": {Name: "Controller Died (within 3 days)", Description: "", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["Other Controller DIED"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}],"logPeriodUnit":"LOG_PERIOD_DAY","logPeriodValue":"3"}`},
	"51678e47-bbc2-4b61-8fad-a8b7e2777ca0": {Name: "Multiple ASCQ:1100 Errors ", Description: "ASCQ:1100 Errors by Encl & Disk (minimum 4 per minute)", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_TIMESTAMP","values":["1689889345"],"valueCondition":"VALUE_CONDITION_LTE"},{"column":"LOG_COLUMN_MESSAGE","values":["ASCQ:1100"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}],"logFrequencyUnit":"LOG_PERIOD_MINUTE","logFrequencyValue":"1","logFrequencyThreshold":"4"}`},
	"2843be5e-4d55-49c2-9a0d-746656b0c4e8": {Name: "Recent Failed Drives", Description: "Failed drives up to 1 month ago", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["SET FAILED|MEMBER CHANGE"],"valueCondition":"VALUE_CONDITION_REGEXP_MATCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}],"logPeriodUnit":"LOG_PERIOD_MONTH","logPeriodValue":"1"}`},
	"b1296856-9c59-445a-9a4c-4253c73ae413": {Name: "20+ ASCQ:4b04 by Encl & Disk", Description: "Enclosures & Disks with more than 20 Errors per hour", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_EVENT","values":["LOG_AMPD_MPI_DSK_SCSI_D_SENSE_DATA"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_MESSAGE","columnRegexpExtract":"(ES:(\\w+)|(ASCQ:(\\w+))|PD:(\\w+))","values":["ASCQ:4b04"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}],"logFrequencyUnit":"LOG_PERIOD_HOUR","logFrequencyValue":"1","logFrequencyThreshold":"20"}`},
	"5105020d-2a6f-405c-a023-236afedf779b": {Name: "Call Trace", Description: "Call Trace in messages", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["\"Call Trace\""],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}],"logPeriodUnit":"LOG_PERIOD_DAY","logPeriodValue":"1"}`},
	"ba6a0b44-b447-4687-a3fe-01678fc08f20": {Name: "Partial Ready Drives", Description: "Partial Ready Drives", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SEVERITY","values":["1"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_EVENT","values":["LOG_ST_DRIVE_PARTIAL_READY"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"c44630af-440e-4aa8-a5f0-aef4a3fb6a8a": {Name: "Key b Errors", Description: "", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_MESSAGE","values":["SK:0b"],"valueCondition":"VALUE_CONDITION_SEARCH"}]}`},
	"ce4ccbc2-26d2-40b2-aeb5-71be358c0d97": {Name: "Lustre log dump", Description: "Lustre log dump", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_COMPONENT","values":["Lustre"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_MESSAGE","values":["dumping log"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"39456a99-2eb8-4c41-b015-93ebbcc21bd3": {Name: "LBUG", Description: "An LBUG has occurred", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["LBUG"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"5c69411c-8498-4e5b-b588-aec22aba53ec": {Name: "Log ST Member Change", Description: "", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_EVENT","values":["LOG_ST_MEMBER_CHANGE"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"8be1febc-b6ae-4009-b764-7708c83262f0": {Name: "ASCQ:1100 Errors", Description: "System has disk errors", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["ASCQ:1100"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"d8e6501e-042e-4a3d-b951-c7082f32c482": {Name: "Has ASCQ:4b0 Errors", Description: "System has disk errors", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["ASCQ:4b0"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"f8fe37f3-b530-4de3-bafc-02e248bd406a": {Name: "Read-only mounting", Description: "Filesystem has remounted as read-only", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_MESSAGE","values":["remounting filesystem read-only"],"valueCondition":"VALUE_CONDITION_SEARCH"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["exascaler"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"027e56e4-4801-4c79-bbd5-ac8ad328aa5c": {Name: " Timed out tx: active_txs", Description: " Timed out tx: active_txs (Mellanox issues)", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_EVENT","values":["Timed out tx: active_txs"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
	"3196d1cd-1637-4a7a-bbed-67c229cf9f89": {Name: "Controller Startup", Description: "Highlights system startup and SFA version number for upgrade dates", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_MESSAGE","values":["Unified Startup"],"valueCondition":"VALUE_CONDITION_SEARCH"}]}`},
	"659a5ea8-be4b-49b9-bc45-f4813397909e": {Name: "Slow Drive Detected", Description: "Slow Drive Detected", Severity: "warning", Query: `{"filters":[{"column":"LOG_COLUMN_SEVERITY","values":["0"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_EVENT","values":["LOG_AMPD_SLOW_DRIVE_DETECTED"],"valueCondition":"VALUE_CONDITION_EQUAL"},{"column":"LOG_COLUMN_SYSTEM_TYPE","values":["sfa"],"valueCondition":"VALUE_CONDITION_EQUAL"}]}`},
}
